# -*- coding: utf-8 -*-
"""MM PS - 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNsILqBUjfTP9zWdpfqbAE6NPqUKWm3P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pt
from scipy import stats
from sklearn.linear_model import LinearRegression
import datetime

"""#Question - 1"""

file = pd.read_csv(r'/content/sample_data/Titan_Dataset.csv')

Open=np.array(file['Open Price'])
Close=np.array(file['Close Price'])
High=np.array(file['High Price'])
Low=np.array(file['Low Price'])

def calculate_y(intercept, slope, Temp):
    y0=[]
    for i in range(0,len(Temp)):
        dummy=0
        dummy=intercept+(slope*Temp[i])
        y0.append(dummy)
    return y0
    
        
slope,intercept,r,p,std_err=stats.linregress(Open,Close)
Close_P=calculate_y(intercept, slope, Open)

pt.title('close vs open')     
t1,p1=stats.ttest_ind(Close,Close_P)
print("T-test value(Linear Reg): ",p1)   
pt.scatter(Open,Close)
pt.plot(Open,Close_P)
pt.show()

corr1=np.corrcoef(Open,Close,rowvar=False)

print("Coorelation (Open vs Close): ",corr1)

slope,intercept,r,p,std_err=stats.linregress(Low,High)
High_P=calculate_y(intercept, slope, Low)

pt.title('High vs Low')       
pt.scatter(Low,High)
pt.plot(Low,High_P)
pt.show()
corr2=np.corrcoef(Low,High,rowvar=False)
print("Coorelation (Low vs High): ",corr2)

def MultipleLinearReg():
    y0=[]
    for i in range(0,len(Open)):
        dummy=mlr.intercept_+(mlr.coef_[0]*Open[i])+(mlr.coef_[1]*High[i])+(mlr.coef_[2]*Low[i])
        y0.append(dummy)
    return y0

Data=pd.DataFrame([Open,High,Low])
#print(Data)
mlr = LinearRegression()
mlr.fit(Data.transpose(),Close)
print(mlr.intercept_)
print(mlr.coef_)

y0=MultipleLinearReg()

t,p=stats.ttest_ind(Close,y0)
print("T-test value: ",p)

pt.title('Multiple Linear Regression')   
dates = [pd.to_datetime(x) for x in file['Date']]   
pt.plot(np.array(dates),y0)
pt.plot(np.array(dates),Close)
pt.xlabel("Date")
pt.ylabel("Close Price")
pt.show()

#trend
if(p<p1):
    print("Linear Reg is better is better in prediction")
else:
    print("Multiple Linear Regression is better in prediction")